Add a quick to check you are running in the correct location

diff --git a/utils/FullTopBuild b/utils/FullTopBuild
--- a/utils/FullTopBuild
+++ b/utils/FullTopBuild
@@ -29,6 +29,16 @@ function nl_error {
   exit 1
 }
 
+alldirs=yes
+for dir in QNX6 nortutil nortlib2 cmdgen oui tmcalgo snafu table qclicomp; do
+  if [ ! -d $dir ]; then
+    echo "Directory $dir not found" >&2
+    alldirs=no
+  fi
+done
+[ $alldirs = yes ] || nl_error "Are you in the correct directory?"
+
+
 if [ `id -u` != 0 ]; then
   exec sudo $0
   nl_error exec failed
